### PR TITLE
add alias for acorn project cli

### PR DESCRIPTION
**Pull request by keyallis**
### Checklist
- [ ] The title of this PR would make a good line in Acorn's Release Note's Changelog
- [ ] The title of this PR ends with a link to the main issue being address in parentheses, like: `This is a title (#1216)`. [Here's an example](https://github.com/acorn-io/runtime/pull/1199)
- [ ] All relevant issues are referenced in the PR description. *NOTE: don't use [GitHub keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that auto-close issues*
- [ ] Commits follow [contributing guidance](https://github.com/acorn-io/runtime/blob/main/CONTRIBUTING.md#commits)
- [ ] Automated tests added to cover the changes. If tests couldn't be added, an explanation is provided in the Verification and Testing section
- [ ] Changes to user-facing functionality, API, CLI, and upgrade impacts are clearly called out in PR description
- [ ] PR has at least two approvals before merging (or a reasonable exception, like it's just a docs change)

### CODE REVIEW

**Review by StrongMonkey — APPROVED** [review]
assuming we have syntax approval from leadership team

**Review by g-linville — APPROVED** [review]

**Comment by ibuildthecloud** [comment]
This is kind of weird. Why `proj`?

**Comment by keyallis** [comment]
> This is kind of weird. Why `proj`?

`acorn p` is too short to distinguish it from pull/push/ps and `proj` seems like the most logical shortening since it's just the first syllable.

**Comment by ibuildthecloud** [comment]
I still think it's weird. I think at that point I just use tab complete. I'm fine with it though. No real harm.

**Pull request merged**
