### PR TITLE
ComputeClass request downscaling for overprovisioning (#2381)

### PR DESCRIPTION
**Pull request by keyallis**
#2381 

Add support for scaling down memory requests for acorns in relation to memory limits. We handle ComputeClasses that do not have this field set (ie legacy ComputeClasses) as having a 1:1 mapping. This means all existing tests should continue to work and behave as expected, so all new tests are only used to cover the new field itself.

### Checklist
- [ ] The title of this PR would make a good line in Acorn's Release Note's Changelog
- [ ] The title of this PR ends with a link to the main issue being address in parentheses, like: `This is a title (#1216)`. [Here's an example](https://github.com/acorn-io/runtime/pull/1199)
- [ ] All relevant issues are referenced in the PR description. *NOTE: don't use [GitHub keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that auto-close issues*
- [ ] Commits follow [contributing guidance](https://github.com/acorn-io/runtime/blob/main/CONTRIBUTING.md#commits)
- [ ] Automated tests added to cover the changes. If tests couldn't be added, an explanation is provided in the Verification and Testing section
- [ ] Changes to user-facing functionality, API, CLI, and upgrade impacts are clearly called out in PR description
- [ ] PR has at least two approvals before merging (or a reasonable exception, like it's just a docs change)

### CODE REVIEW

**Review by thedadams — APPROVED** [review]
One nit. Otherwise, looks good to me.

**Review by tylerslaton — APPROVED** [review]
This looks good, I'm trying to imagine a situation where we want to scale up *above* the defined memory such that `1.25` would be a valid scalar. The thing I'm imagining is where an admin wants to allocate more memory than the user defined. Is that something we'd want?

If not this is good to go in my mind.

**Comment by g-linville** [comment]
I'm just now starting to look at the code, but one thing I am noticing is that `scalar` needs to be replaced with `scaler` everywhere it appears. We're calling it a "scaler" because it determines the scale of the memory request in comparison to the limit. Mathematically speaking it is also a "scalar" since it is a single numerical value and not a vector, but that is not what we should name it lol.

**Review by g-linville — CHANGES_REQUESTED** [review]
Lgtm other than the naming change that I mentioned in my previous comment.

**Review by g-linville — APPROVED** [review]

**Pull request merged**
